### ISSUE TITLE
Fix maintenance message regarding package submissions

### ISSUE THREAD

**Issue by ferventcoder** [silarsis/choco-docker-machine#1]
https://github.com/silarsis/choco-docker-machine/blob/master/MAINTENANCE.md#5-upload-the-package

> CAUTION: You can upload a version only once (chocolatey does not allow overwriting packages). Therefore be careful since you can do this step only once without changing <version> string.

Note that this isn't completely accurate - you can resubmit the package version numerous times until it is approved.

**Comment by silarsis** [comment]
thanks, noted :)
